### ISSUE TITLE
einat firewall rules?

### ISSUE THREAD

**Issue by vortexilation** [muink/openwrt-einat-ebpf#1]
Hello @muink,

   for now I am disabling CONFIG_BUILD_NLS and get back on track, regarding the einat OpenWrt rules,
```
You would also need to disable IP masquerading for WAN firewall zone and allow inbound traffic forwarding from WAN to LAN, that can be done in Luci - Firewall page.
```

Can you please share me your firewall file or part of it regarding einat?.

**Comment by vortexilation** [comment]
Tried : 
![image](https://github.com/muink/openwrt-einat-ebpf/assets/60100560/085db769-315c-4cff-b413-2caacfb8cbc7)

But doesn't work, no internet connectivity or [NatTypeTester](https://github.com/HMBSbige/NatTypeTester) is failed.

Connection being made through PPPoe.

**Comment by muink** [comment]
There is no need to manually configure the firewall. The firewall configuration has been implemented in the [init script](https://github.com/muink/openwrt-einat-ebpf/blob/6e74c1ef10fa3f62409d9ff5351d9f3decbf9150/files/einat.init#L74-L104).

**Comment by vortexilation** [comment]
Where I can see or edit those firewall rules that are created by the einat init?

Also whenever restarting firewall there are : 
```
root@OpenWrt:~# service firewall restart
ubus rule (ubus:einat[einat] rule 0) option 'src' specifies invalid value ''
ubus rule (ubus:einat[einat] rule 0) skipped due to invalid options
ubus rule (ubus:einat[einat] rule 1) option 'src' specifies invalid value ''
ubus rule (ubus:einat[einat] rule 1) skipped due to invalid options
ubus nat (ubus:einat[einat] nat 2) option 'src' specifies invalid value ''
ubus nat (ubus:einat[einat] nat 2) skipped due to invalid options
Section @include[2] option 'reload' is not supported by fw4
```

With current condition, using [NatTypeTester](https://github.com/HMBSbige/NatTypeTester) result is "PortRestrictedCone"

**Comment by vortexilation** [comment]
Getting FullCone after enlarging ports range - 20000-65535 👍

**Comment by vortexilation** [comment]
> root@OpenWrt:~# service firewall restart
> ubus rule (ubus:einat[einat] rule 0) option 'src' specifies invalid value ''
> ubus rule (ubus:einat[einat] rule 0) skipped due to invalid options
> ubus rule (ubus:einat[einat] rule 1) option 'src' specifies invalid value ''
> ubus rule (ubus:einat[einat] rule 1) skipped due to invalid options
> ubus nat (ubus:einat[einat] nat 2) option 'src' specifies invalid value ''
> ubus nat (ubus:einat[einat] nat 2) skipped due to invalid options
> Section @include[2] option 'reload' is not supported by fw4

Still opening this issues cause wanted to see your opinion on warning when restarting firewall.

**Comment by muink** [comment]
> Where I can see or edit those firewall rules that are created by the einat init?

`fw4 print` (Only managed by fw4) or `nft list table inet fw4` (All)

> > option 'src' specifies invalid value ''

Looks like you didn't specify (or the correct) `ifname` in `/etc/config/einat`

**Comment by vortexilation** [comment]
I've set ifname as "pppoe-wan", should I set as eth5 which is the physical interface name?.

I have configured it through luci-app-einat.

Also I have tested einat-ebpf seems slower than [nft-fullcone](https://github.com/fullcone-nat-nftables/nft-fullcone).

For example I have issue loading videos in reddit and some site.

**Comment by muink** [comment]
> I've set ifname as "pppoe-wan", should I set as eth5 which is the physical interface name?.

Yes.

You can find physical interface name with `ip addr`.
And use `fw4 device $ifname` to confirm whether it is available.

**Comment by vortexilation** [comment]
```
17: eth5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:2a brd ff:ff:ff:ff:ff:ff
30: pppoe-wan: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc cake state UNKNOWN group default qlen 3
    link/ppp 
    inet 123.123.123.123 peer 123.123.123.1/32 scope global pppoe-wan
       valid_lft forever preferred_lft forever
    inet6 xxxx::xxxx:xxxx:xxxx:xxxx peer xxxx::xxxx:xxxx:xxxx:xxxx/128 scope link 
       valid_lft forever preferred_lft forever


root@OpenWrt:~# fw4 device eth5
root@OpenWrt:~# fw4 device pppoe-wan
wan
```

pppoe-wan is being dialed through eth5, should I use eth5 or pppoe-wan?

**Comment by vortexilation** [comment]
No matter what I've tried eth5 or pppoe-wan as ifname/wan, I am still getting
```
ubus rule (ubus:einat[einat] rule 0) option 'src' specifies invalid value ''
ubus rule (ubus:einat[einat] rule 0) skipped due to invalid options
ubus rule (ubus:einat[einat] rule 1) option 'src' specifies invalid value ''
ubus rule (ubus:einat[einat] rule 1) skipped due to invalid options
ubus nat (ubus:einat[einat] nat 2) option 'src' specifies invalid value ''
ubus nat (ubus:einat[einat] nat 2) skipped due to invalid options
```
When restarting firewall

**Comment by muink** [comment]
> root@OpenWrt:~# fw4 device pppoe-wan
wan

Looks like `pppoe-wan` is the correct ifname.
The broadband access method in my area is not pppoe, so I cannot test it.
Is it possible to provide the output of the following two items when ifname=pppoe-wan?
```
export EINAT_DEBUG=1
/etc/init.d/einat reload
```

```
fw4 print
```

**Comment by vortexilation** [comment]
```
root@OpenWrt:~# /etc/init.d/einat reload
config enabled='1'
config bpf_log_level='3'
config nat44='1'
config nat66='0'
config ifname='pppoe-wan'
config ports='20000-65535'
config hairpin_enabled='0'
config hairpinif='lo br-lan'
```

fw4 print : 
[fw4.log](https://github.com/user-attachments/files/15895542/fw4.log)

**Comment by muink** [comment]
```
config ifname='pppoe-wan'
```

```
	chain accept_to_lan {
		oifname "br-lan" counter accept comment "!fw4: accept lan IPv4/IPv6 traffic"
	}

	chain forward_wan {
		meta nfproto ipv4 meta l4proto tcp counter jump accept_to_lan comment "!fw4: ubus:einat[einat] rule 1"
		meta nfproto ipv4 meta l4proto udp counter jump accept_to_lan comment "!fw4: ubus:einat[einat] rule 1"
		meta nfproto ipv4 meta l4proto icmp counter jump accept_to_lan comment "!fw4: ubus:einat[einat] rule 1"
		ct status dnat accept comment "!fw4: Accept port forwards"
		jump reject_to_wan
	}

	chain srcnat_wan {
		meta nfproto ipv4 meta l4proto tcp counter accept comment "!fw4: ubus:einat[einat] nat 2"
		meta nfproto ipv4 meta l4proto udp counter accept comment "!fw4: ubus:einat[einat] nat 2"
		meta nfproto ipv4 meta l4proto icmp counter accept comment "!fw4: ubus:einat[einat] nat 2"
		meta nfproto ipv4 masquerade comment "!fw4: Masquerade IPv4 wan traffic"
	}
```
It seems to me that the firewall setup is correctly.

You can check `src` by following command:
`/etc/init.d/einat info | jq '.einat.instances["einat"].data.firewall'`

If `"src": <firewall zone of pppoe-wan>`， then there is no problem.

**Comment by vortexilation** [comment]
@muink 
Thanks, it's working but I have experiencing some slowdown (browsing site) than using nft-fullcone solution.

Do you use einat-ebf on daily basis or production?

**Comment by muink** [comment]
Yes. Maybe I'm not sensitive to speed and didn't feel the difference.

**Comment by vortexilation** [comment]
Thank you, closing this one.
