### ISSUE TITLE
想编译进openwrt24.10，github Actions云编译 ubuntu24.04环境下报错

### ISSUE THREAD

**Issue by zow2023** [muink/openwrt-einat-ebpf#2]
error: failed to run custom build command for `libbpf-sys v1.5.0+v1.5.0`  Caused by:   process didn't exit successfully: `/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/einat-ebpf-0.1.2/target/release/build/libbpf-sys-c14210cca91e0978/build-script-build` (exit status: 101)   --- stderr   /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found   thread 'main' panicked at /workdir/openwrt/dl/cargo/registry/src/index.crates.io-6f17d22bba15001f/libbpf-sys-1.5.0+v1.5.0/build.rs:90:10:   Unable to generate bindings: ClangDiagnostic("/usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found\n")   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace error: failed to compile `einat v0.1.2 (/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/einat-ebpf-0.1.2)`, intermediate artifacts can be found at `/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/einat-ebpf-0.1.2/target`. To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path. make[3]: *** [Makefile:93: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/einat-ebpf-0.1.2/.built] Error 101 make[3]: Leaving directory '/workdir/openwrt/package/einat-ebpf' time: package/einat-ebpf/compile#0.48#0.31#1.09 
    ERROR: package/einat-ebpf failed to build.

**Comment by muink** [comment]
Currently, only Stable Release is adapted.

**Comment by zow2023** [comment]
我改用官方的v23.05.5也不能编译成功，按照说明开启内核的那些配置，。
 Compile-time checks and compiler options
*
Compile the kernel with debug info (DEBUG_INFO) [Y/n/?] y
  Reduce debugging information (DEBUG_INFO_REDUCED) [N/y/?] n
  Compressed debugging information (DEBUG_INFO_COMPRESSED) [N/y/?] n
  Produce split debuginfo in .dwo files (DEBUG_INFO_SPLIT) [N/y/?] n
  DWARF version
  > 1. Rely on the toolchain's implicit default DWARF version (DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT)
    2. Generate DWARF Version 4 debuginfo (DEBUG_INFO_DWARF4)
    3. Generate DWARF Version 5 debuginfo (DEBUG_INFO_DWARF5)
  choice[1-3?]: 1
  Generate BTF type information (DEBUG_INFO_BTF) [Y/n/?] y
make[7]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[6]: *** [Makefile:628: syncconfig] Error 2
Makefile:725: include/config/auto.conf.cmd: No such file or directory
make[5]: *** [Makefile:748: include/config/auto.conf.cmd] Error 2
make[4]: *** [Makefile:18: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.15.167/.modules] Error 2
  Generate BTF type information for kernel modules (DEBUG_INFO_BTF_MODULES) [Y/n/?] (NEW) make[5]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.15.167'
make[3]: *** [Makefile:11: compile] Error 2
make[4]: Leaving directory '/workdir/openwrt/target/linux/mediatek'
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/compile#0.88#0.65#1.48
    ERROR: target/linux failed to build.

**Comment by muink** [comment]
kernel build reference for 24.10:
1. https://github.com/fantastic-packages/rebuild/blob/conf-24.10/default/buildinfo.sh#L35
2. https://github.com/fantastic-packages/rebuild/blob/conf-24.10/.github/workflows/rebuild.yml#L239
