### ISSUE TITLE
使用请教：启用插件后，国内的网站打不开，微信的网速也很慢，但是能用，不会显示无网络，。

### ISSUE THREAD

**Issue by zow2023** [muink/openwrt-einat-ebpf#3]
费了很大的劲在官方的V23.05.5编译大佬的这个插件，启用后整个网络不能正常使用：主要的是国内的网站基本都打不开，在帕斯窝是否启用的前提下都是这样的情况；我关掉代理软件，网络-防火墙-软件流量分载（开和关都试过）都是这种情况。实在是菜。特来请教。
我是光猫桥接，路由器拨号上网。下面是我根据您前面答复其他网友的问题留下的参考资料，根据自己的情况的截图。
![2024-11-27 19-50-13](https://github.com/user-attachments/assets/72af1f85-e15f-4902-b546-b4998063074b)
![2024-11-27 19-51-50](https://github.com/user-attachments/assets/9496042a-cb5e-4934-acd6-b4954d0eb2a3)
![2024-11-27 19-52-13](https://github.com/user-attachments/assets/080fdfba-362a-46da-91d3-4da3d836dc56)

**Comment by muink** [comment]
这个在目前的openwrt官方23.05是用不了的
因为要重新编译kernel，等于要重编译一次openwrt

readme里也提到过，需要immortalwrt或fantastic-rebuild这种有启用对应的内核选项的发行版本

您完全可以使用immortalwrt搭配预编译的ipk使用

**Comment by muink** [comment]
看了您之前发的issuse
1. 24.10版本的实际已经编译出来了 https://github.com/fantastic-packages/packages/blob/gh-pages/releases%2F24.10%2Fpackages%2Fx86_64%2Fspecial%2Feinat-ebpf-0.1.4-r4.apk

2. 要编译开启内核选项的openwrt
请参看下面链接项目，23.05.4开始的openwrt版本都有这个bug。部分内核选项会被忽略，需要手动添加https://github.com/fantastic-packages/rebuild/blob/conf/.github%2Fworkflows%2Frebuild.yml#L227-L227

3. 在编译软件包部分，可以参考下面链接部分，
新版本的einat又多了些主机依赖
https://github.com/fantastic-packages/packages/blob/master/.github%2Fworkflows%2Fcompile.yml#L212-L212

4. 这里的讨论也可以参考
https://github.com/EHfive/einat-ebpf/discussions/22#discussioncomment-11309957

**Comment by zow2023** [comment]
感谢您第一时间回复。
1.我的是mediatek-7622的硬路由，在您编译的IPK中没有找到对应的einat-ebpf包，只有luci和语言包。
2.我是在修改了官方v23.05.5源码的kernel.in文件，在其中添加了内核选项原本不显示的那一项的代码，才编译成功。我也试过在天灵的v23.05.4中编译您的这个插件，成功了，可是打开后网络就不通了，，我不知道是不是他的固件自带的防火墙中的[nft-fullcone] 有影响，，。我还没试过的方式是----直接用他的固件安装您编好的插件。我稍后试下。
3.再次感谢回复和指教。

**Comment by muink** [comment]
mediatek-7622 的话，选 aarch64_cortex-a53 架构
einat-ebpf 包，一直都在 special 分类里 https://fantastic-packages.github.io/packages/releases/23.05/packages/aarch64_cortex-a53/special/
我没有 mediatek-7622 的设备，所以没办法进一步测试
我帮您编译一个固件版本，您也可以测试下 https://github.com/fantastic-packages/rebuild/actions/workflows/rebuild.yml

**Comment by zow2023** [comment]
我刚才试过天灵的23.05.4固件安装您编好的插件，一打开就没网络 了  显示的具体logo 跟我上面截图的一样,.
我刚才试了下最新的24.10源码，安装您编好的固件，测了下 可以了 。
![2024-11-28 11-38-52](https://github.com/user-attachments/assets/9aa16900-6432-456c-8772-fa5be289a783)
![微信截图_20241128113939](https://github.com/user-attachments/assets/62392805-2969-4ba5-8186-c525e91cd4e8)
看来只能在24.10上用这个软件了，另外请教下 这个插件在同时启用DAED时 有必要开启吗？有影响吗？

**Comment by zow2023** [comment]
我没仔细看您的答复，抱歉。我现在才看到您帮我编译的那个是没成功的 。我是在您23.05.5目录下下载的这个： https://fantastic-packages.github.io/packages/releases/23.05/packages/aarch64_cortex-a53/special/，用在24.10固件上，上面的截图就是的。在开启luci-app-daed时，网络会间歇性的断网。看来einat-ebpf和大鹅之间有冲突，同时启用的话。

**Comment by muink** [comment]
和大鹅可能会有冲突的, 稳妥的方式是einat装在上级网关, dae装在下级网关, 并且dae的网关不进行dhcp分配与上级网关保持同一子网
